language: go
install: false
go:
  - 1.11.x
go_import_path: github.com/gritzko/ron
matrix:
  include:
    - name: "RON"
      script: go test -timeout 5s
    - name: "CRDTs"
      script: cd rdt && go test -timeout 5s
