package ron

var PUNCT, BITS [128]int8

// bit-separator conversions generated by ./sep2bits.pl on
// Tue Jan  2 23:55:29 +05 2018
// from
// commit d45ec074ef7bc44670f39277ad623973ed317314
// Author: Victor Grishchenko <victor.grishchenko@gmail.com>
// Date:   Thu Dec 28 23:15:55 2017 +0500
//
//     batch.Equal() to ignore frame borders

const SPEC_KIND = 1

var SPEC_PUNCT = []byte("*#@:")

const SPEC_TYPE_SEP = '*'
const SPEC_OBJECT_SEP = '#'
const SPEC_EVENT_SEP = '@'
const SPEC_REF_SEP = ':'
const SPEC_TYPE = 0
const SPEC_OBJECT = 1
const SPEC_EVENT = 2
const SPEC_REF = 3

const UUID_KIND = 2

var UUID_PUNCT = []byte("$%+-")

const UUID_NAME_SEP = '$'
const UUID_HASH_SEP = '%'
const UUID_EVENT_SEP = '+'
const UUID_DERIVED_SEP = '-'
const UUID_NAME = 0
const UUID_HASH = 1
const UUID_EVENT = 2
const UUID_DERIVED = 3

const ATOM_KIND = 3

var ATOM_PUNCT = []byte(">='^")

const ATOM_UUID_SEP = '>'
const ATOM_INT_SEP = '='
const ATOM_STRING_SEP = '\''
const ATOM_FLOAT_SEP = '^'
const ATOM_UUID = 0
const ATOM_INT = 1
const ATOM_STRING = 2
const ATOM_FLOAT = 3

const TERM_KIND = 4

var TERM_PUNCT = []byte(";,!?")

const TERM_RAW_SEP = ';'
const TERM_REDUCED_SEP = ','
const TERM_HEADER_SEP = '!'
const TERM_QUERY_SEP = '?'
const TERM_RAW = 0
const TERM_REDUCED = 1
const TERM_HEADER = 2
const TERM_QUERY = 3

const REDEF_KIND = 5

var REDEF_PUNCT = []byte("`\\|/")

const REDEF_PREV_SEP = '`'
const REDEF_OBJECT_SEP = '\\'
const REDEF_EVENT_SEP = '|'
const REDEF_REF_SEP = '/'
const REDEF_PREV = 0
const REDEF_OBJECT = 1
const REDEF_EVENT = 2
const REDEF_REF = 3

const PREFIX_KIND = 6

var PREFIX_PUNCT = []byte("([{}])")

const PREFIX_PRE4_SEP = '('
const PREFIX_PRE5_SEP = '['
const PREFIX_PRE6_SEP = '{'
const PREFIX_PRE7_SEP = '}'
const PREFIX_PRE8_SEP = ']'
const PREFIX_PRE9_SEP = ')'
const PREFIX_PRE4 = 0
const PREFIX_PRE5 = 1
const PREFIX_PRE6 = 2
const PREFIX_PRE7 = 3
const PREFIX_PRE8 = 4
const PREFIX_PRE9 = 5

const BASE_KIND = 7

var BASE_PUNCT = []byte("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz~")

const BASE_0_SEP = '0'
const BASE_1_SEP = '1'
const BASE_2_SEP = '2'
const BASE_3_SEP = '3'
const BASE_4_SEP = '4'
const BASE_5_SEP = '5'
const BASE_6_SEP = '6'
const BASE_7_SEP = '7'
const BASE_8_SEP = '8'
const BASE_9_SEP = '9'
const BASE_10_SEP = 'A'
const BASE_11_SEP = 'B'
const BASE_12_SEP = 'C'
const BASE_13_SEP = 'D'
const BASE_14_SEP = 'E'
const BASE_15_SEP = 'F'
const BASE_16_SEP = 'G'
const BASE_17_SEP = 'H'
const BASE_18_SEP = 'I'
const BASE_19_SEP = 'J'
const BASE_20_SEP = 'K'
const BASE_21_SEP = 'L'
const BASE_22_SEP = 'M'
const BASE_23_SEP = 'N'
const BASE_24_SEP = 'O'
const BASE_25_SEP = 'P'
const BASE_26_SEP = 'Q'
const BASE_27_SEP = 'R'
const BASE_28_SEP = 'S'
const BASE_29_SEP = 'T'
const BASE_30_SEP = 'U'
const BASE_31_SEP = 'V'
const BASE_32_SEP = 'W'
const BASE_33_SEP = 'X'
const BASE_34_SEP = 'Y'
const BASE_35_SEP = 'Z'
const BASE_36_SEP = '_'
const BASE_37_SEP = 'a'
const BASE_38_SEP = 'b'
const BASE_39_SEP = 'c'
const BASE_40_SEP = 'd'
const BASE_41_SEP = 'e'
const BASE_42_SEP = 'f'
const BASE_43_SEP = 'g'
const BASE_44_SEP = 'h'
const BASE_45_SEP = 'i'
const BASE_46_SEP = 'j'
const BASE_47_SEP = 'k'
const BASE_48_SEP = 'l'
const BASE_49_SEP = 'm'
const BASE_50_SEP = 'n'
const BASE_51_SEP = 'o'
const BASE_52_SEP = 'p'
const BASE_53_SEP = 'q'
const BASE_54_SEP = 'r'
const BASE_55_SEP = 's'
const BASE_56_SEP = 't'
const BASE_57_SEP = 'u'
const BASE_58_SEP = 'v'
const BASE_59_SEP = 'w'
const BASE_60_SEP = 'x'
const BASE_61_SEP = 'y'
const BASE_62_SEP = 'z'
const BASE_63_SEP = '~'
const BASE_0 = 0
const BASE_1 = 1
const BASE_2 = 2
const BASE_3 = 3
const BASE_4 = 4
const BASE_5 = 5
const BASE_6 = 6
const BASE_7 = 7
const BASE_8 = 8
const BASE_9 = 9
const BASE_10 = 10
const BASE_11 = 11
const BASE_12 = 12
const BASE_13 = 13
const BASE_14 = 14
const BASE_15 = 15
const BASE_16 = 16
const BASE_17 = 17
const BASE_18 = 18
const BASE_19 = 19
const BASE_20 = 20
const BASE_21 = 21
const BASE_22 = 22
const BASE_23 = 23
const BASE_24 = 24
const BASE_25 = 25
const BASE_26 = 26
const BASE_27 = 27
const BASE_28 = 28
const BASE_29 = 29
const BASE_30 = 30
const BASE_31 = 31
const BASE_32 = 32
const BASE_33 = 33
const BASE_34 = 34
const BASE_35 = 35
const BASE_36 = 36
const BASE_37 = 37
const BASE_38 = 38
const BASE_39 = 39
const BASE_40 = 40
const BASE_41 = 41
const BASE_42 = 42
const BASE_43 = 43
const BASE_44 = 44
const BASE_45 = 45
const BASE_46 = 46
const BASE_47 = 47
const BASE_48 = 48
const BASE_49 = 49
const BASE_50 = 50
const BASE_51 = 51
const BASE_52 = 52
const BASE_53 = 53
const BASE_54 = 54
const BASE_55 = 55
const BASE_56 = 56
const BASE_57 = 57
const BASE_58 = 58
const BASE_59 = 59
const BASE_60 = 60
const BASE_61 = 61
const BASE_62 = 62
const BASE_63 = 63

const FRAME_KIND = 8

var FRAME_PUNCT = []byte(".")

const FRAME_TERM_SEP = '.'
const FRAME_TERM = 0

var ABC = [128]int8{-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, -1, 1, 0, 1, -1, 2, 0, 5, 0, 2, 1, 3, 0, 3, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 0, -1, 1, 0, 3, 2, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 1, 1, 4, 3, 36, 0, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 2, 2, 3, 63, -1}

var ABC_KIND = [128]int8{-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 4, -1, 1, 2, 2, -1, 3, 6, 6, 1, 2, 4, 2, 8, 5, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 1, 4, -1, 3, 3, 4, 1, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 5, 6, 3, 7, 5, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 5, 6, 7, -1}
